image: maven:latest

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean
    - mvn install

  only:
    - master

containerize:
  # image: docker:latest
  stage: deploy
  image: docker:18-git
  services:
    - docker:18-dind
      command: ["--experimental"]
  
  before_script:
    - docker version
    - export PATH=$PATH:~/.docker/cli-plugins/docker-buildx

  script:
    - docker buildx build .
    - docker tag abcd .
    - docker images
  only:
    - master
