image: maven:latest

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean
    - mvn install

  only:
    - master

containerize:
  image: ubuntu:latest
  stage: deploy
  # services:
  #   - name: docker:dind
  #     command: ["--experimental"]
  
  before_script:
    # Preparing wget
    # - apt-get remove docker docker-engine docker.io
    - apt-get update -y
    - apt-get upgrade -y
    - apt install docker.io
    - systemctl start docker
    - systemctl enable docker
    - docker version
    - export PATH=$PATH:~/.docker/cli-plugins/docker-buildx
    - apt-get update -y
    - apt-get upgrade -y
    # --platform linux/amd64,linux/arm64

  script:
    - docker buildx build .
    - docker tag abcd .
    - docker images
  only:
    - master

# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - master