image: maven:latest

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean
    - mvn install

  only:
    - master

containerize:
  
  stage: deploy
  image: ubuntu:latest
  services:
    - docker:18-dind
      command: ["--experimental"]
  
  before_script:
    - docker version
    # - export PATH=$PATH:~/.docker/cli-plugins/docker-buildx

  script:
    - docker buildx build .
    - docker tag abcd .
    - docker images
  only:
    - master
