image: maven:latest

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
#   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean
    - mvn install

  only:
    - master

containerize:
  image: ubuntu:latest
  stage: deploy
  services:
    - name: docker:dind
      command: ["--experimental"]
  
  script:
    - docker buildx build arch arm64 .
    - docker tag abcd .
  only:
    - master

# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS deploy
#   only:
#     - master