language: java
jdk:
  - openjdk11

sudo: required
 
services:
  - docker

cache:
  directories:
  - $HOME/.m2

env:
  - MAVEN_VERSION=3.6.3
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
# script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"


script:
  - maven clean
  - mvn install

after_success:
  - docker login -u $username -p $password
  = docker build -t sayederfanarefin/raspberrypi-rover
  - docker push sayederfanarefin/raspberrypi-rover:latest
