language: java
jdk:
  - openjdk11

sudo: required

env:
  global:
    - IMAGE_NAME=sayederfanarefin/raspberrypi-rover

services:
  - docker

cache:
  directories:
  - $HOME/.m2

env:
  - MAVEN_VERSION=3.6.3
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"

before_script:
  - docker pull $IMAGE_NAME || true

script:
  - mvn clean
  - mvn install
  - docker buildx build -t abcd .

after_script:
  - docker images

before_deploy:
  - docker login -u $username -p $password
  - docker tag abcd sayederfanarefin/raspberrypi-rover:latest
deploy:
  provider: script
  script: docker push sayederfanarefin/raspberrypi-rover:latest
  on:
    branch: master
