language: java
jdk:
  - openjdk11

sudo: required

env:
  global:
    - IMAGE_NAME=sayederfanarefin/raspberrypi-rover
    - DOCKER_CLI_EXPERIMENTAL=enabled

services:
  - docker

cache:
  directories:
  - $HOME/.m2

env:
  - MAVEN_VERSION=3.6.3
  - experimental=true
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"

before_script:
  - docker version
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - docker version
  # - docker config ls
  # - docker pull $IMAGE_NAME

script:
  - mvn clean
  - mvn install
  # - export DOCKER_CLI_EXPERIMENTAL=enabled
  # - docker buildx create --name newbuilder
  # - docker buildx ls
  # - docker buildx use newbuilder
  # - docker buildx inspect --bootstrap
  # - docker buildx ls
  # - docker buildx build arch arm64 --push -t abcd .
  - docker buildx build .
  - docker tag abcd .
  # - docker buildx build abcd .

after_script:
  - docker images

before_deploy:
  - docker login -u $username -p $password
  - docker tag abcd sayederfanarefin/raspberrypi-rover:latest
deploy:
  provider: script
  script: docker push sayederfanarefin/raspberrypi-rover:latest
  on:
    branch: master
